### ISSUE TITLE
RME Asio Driver X64

### ISSUE THREAD

**Issue by circuitb** [tebjan/VVVV.Audio#171]
hello Tebjan,
there was an old issue but it was closed
https://github.com/tebjan/VVVV.Audio/issues/1

just discovered that RME ASIO FireFace USB driver only work with vvvv x86  versions
all the x64 from beta 33.7 to alpha 38.2 can't start the native Asio Driver (AudioEngine node quickly  turns red)
guess it's related to RME only since if i remember well other Asio capable cards were working

here is the error log of alpha 38.2 x64:

Exception log with detailed tech info. Generated on 12/05/2019 16:26:58.
You may send it to the application vendor, helping him to understand what had happened.
 Application title: 
 Application file: E:\projects\vvvv_50alpha38.2_x64\vvvv.exe
------------------------------------------------------------------------------
Exception class: EClrException
Exception message: Unable to instantiate ASIO. Check if STAThread is set.
Exception address: 0000000000000000
------------------------------------------------------------------------------
System.Runtime.InteropServices.COMException (0x8007007E): Unable to instantiate ASIO. Check if STAThread is set
   at NAudio.Wave.Asio.ASIODriver.initFromGuid(Guid ASIOGuid)
   at NAudio.Wave.Asio.ASIODriver.GetASIODriverByName(String name)
   at NAudio.Wave.AsioOut.InitFromName(String driverName)
   at VVVV.Audio.AudioEngine.ChangeDriverSettings(String driverName, Int32 sampleRate, Int32 inputChannels, Int32 inputChannelOffset, Int32 outputChannels, Int32 outputChannelOffset)
   at VVVV.Nodes.AudioEngineNode.Evaluate(Int32 SpreadMax) in C:\Dev\vvvv\VVVV.Audio\Source\VVVV.Audio.Nodes\AudioEngineNode.cs:line 178
   at VVVV.Hosting.IO.PluginContainer.Evaluate(Int32 spreadMax)
------------------------------------------------------------------------------
Main thread ID = 3816
Exception thread ID = 3816
------------------------------------------------------------------------------
Exception stack
Stack list, generated 12/05/2019 16:26:58
[000000000078FD58]{vvvv.exe    } ClrUtils.ClrCheck (Line 1048, "ClrUtils.pas" + 2)
[000000000090F8CA]{vvvv.exe    } PluginNodes.TMPluginWrapperNode.CalculateNodeAndOutputSliceCounts (Line 1052, "PluginNodes.pas" + 23)
[0000000000A33021]{vvvv.exe    } Graph.TMBasicNode.Prepare (Line 1199, "Graph.pas" + 22)
[0000000000A3693A]{vvvv.exe    } Graph.TMPin._Prepare (Line 2472, "Graph.pas" + 12)
[0000000000A36D1F]{vvvv.exe    } Graph.TMPin._ValidateAllSlices (Line 2520, "Graph.pas" + 10)
[0000000000A33153]{vvvv.exe    } Graph.TMBasicNode.ValidateAllOutputs (Line 1248, "Graph.pas" + 2)
[0000000000A337B9]{vvvv.exe    } Graph.TMBasicNode.PrepareGraph (Line 1404, "Graph.pas" + 2)
[0000000000A33833]{vvvv.exe    } Graph.TMBasicNode.PrepareGraphCB (Line 1410, "Graph.pas" + 3)
[0000000000A2B704]{vvvv.exe    } Events.TMEvent.Call (Line 403, "Events.pas" + 11)
[0000000000A20B05]{vvvv.exe    } MainLoop.TMMainLoop.DoTimer (Line 221, "MainLoop.pas" + 35)
[00000000006DBBB9]{vvvv.exe    } IdleTimer.TMIdleTimer.AppIdle (Line 153, "IdleTimer.pas" + 47)
[00000000005C7E1D]{vvvv.exe    } Vcl.Forms.TApplication.Idle (Line 10743, "Vcl.Forms.pas" + 8)
[00000000005C6978]{vvvv.exe    } Vcl.Forms.TApplication.HandleMessage (Line 10195, "Vcl.Forms.pas" + 2)
[00000000005C6E64]{vvvv.exe    } Vcl.Forms.TApplication.Run (Line 10332, "Vcl.Forms.pas" + 26)
[0000000000DD2D3C]{vvvv.exe    } vvvv.vvvv (Line 162, "" + 9)
[00007FFE08C116AD]{KERNEL32.DLL} BaseThreadInitThunk
[00007FFE0A364629]{ntdll.dll   } RtlUserThreadStart
------------------------------------------------------------------------------
Call stack for main thread
Stack list, generated 12/05/2019 16:26:58
[00007FFE0A38B99A]{ntdll.dll   } ZwGetContextThread
[00000000004E7538]{vvvv.exe    } Vcl.Controls.TWinControl.WndProc (Line 9978, "Vcl.Controls.pas" + 154)
[00000000005B89B0]{vvvv.exe    } Vcl.Forms.TCustomForm.WndProc (Line 4345, "Vcl.Forms.pas" + 202)
[00000000004E67A9]{vvvv.exe    } Vcl.Controls.TWinControl.MainWndProc (Line 9691, "Vcl.Controls.pas" + 5)
[000000000048BF16]{vvvv.exe    } System.Classes.StdWndProc (Line 13896, "System.Classes.pas" + 9)
[00007FFE0A172434]{user32.dll  } Unknown function at DispatchMessageW
[00007FFE0A172297]{user32.dll  } Unknown function at IsThreadDesktopComposited
[00000000005C68F4]{vvvv.exe    } Vcl.Forms.TApplication.ProcessMessage (Line 10164, "Vcl.Forms.pas" + 23)
[00000000005C6968]{vvvv.exe    } Vcl.Forms.TApplication.HandleMessage (Line 10194, "Vcl.Forms.pas" + 1)
[00000000005BFA3D]{vvvv.exe    } Vcl.Forms.TCustomForm.ShowModal (Line 7036, "Vcl.Forms.pas" + 34)
[00000000009702C9]{vvvv.exe    } ExceptionDialog.TExceptionDialog.ShowException (Line 732, "ExceptionDialog.pas" + 37)
[000000000096F408]{vvvv.exe    } ExceptionDialog.TExceptionDialog.ExceptionHandler (Line 531, "ExceptionDialog.pas" + 13)
[0000000000A2D695]{vvvv.exe    } BasicObjects.TMObject.LogErrorFmt (Line 227, "BasicObjects.pas" + 7)
[000000000090F951]{vvvv.exe    } PluginNodes.TMPluginWrapperNode.CalculateNodeAndOutputSliceCounts (Line 1060, "PluginNodes.pas" + 31)
[0000000000A33021]{vvvv.exe    } Graph.TMBasicNode.Prepare (Line 1199, "Graph.pas" + 22)
[0000000000A3693A]{vvvv.exe    } Graph.TMPin._Prepare (Line 2472, "Graph.pas" + 12)
[0000000000A36D1F]{vvvv.exe    } Graph.TMPin._ValidateAllSlices (Line 2520, "Graph.pas" + 10)
[0000000000A33153]{vvvv.exe    } Graph.TMBasicNode.ValidateAllOutputs (Line 1248, "Graph.pas" + 2)
[0000000000A337B9]{vvvv.exe    } Graph.TMBasicNode.PrepareGraph (Line 1404, "Graph.pas" + 2)
[0000000000A33833]{vvvv.exe    } Graph.TMBasicNode.PrepareGraphCB (Line 1410, "Graph.pas" + 3)
[0000000000A2B704]{vvvv.exe    } Events.TMEvent.Call (Line 403, "Events.pas" + 11)
[0000000000A20B05]{vvvv.exe    } MainLoop.TMMainLoop.DoTimer (Line 221, "MainLoop.pas" + 35)
[00000000006DBBB9]{vvvv.exe    } IdleTimer.TMIdleTimer.AppIdle (Line 153, "IdleTimer.pas" + 47)
[00000000005C7E1D]{vvvv.exe    } Vcl.Forms.TApplication.Idle (Line 10743, "Vcl.Forms.pas" + 8)
[00000000005C6978]{vvvv.exe    } Vcl.Forms.TApplication.HandleMessage (Line 10195, "Vcl.Forms.pas" + 2)
[00000000005C6E64]{vvvv.exe    } Vcl.Forms.TApplication.Run (Line 10332, "Vcl.Forms.pas" + 26)
[0000000000DD2D3C]{vvvv.exe    } vvvv.vvvv (Line 162, "" + 9)
[00007FFE08C116AD]{KERNEL32.DLL} BaseThreadInitThunk
[00007FFE0A364629]{ntdll.dll   } RtlUserThreadStart
------------------------------------------------------------------------------
System   : Windows 8.1 Professional, Version: 6.3, Build: 2580, ""
Processor: Intel, Intel(R) Core(TM) i7 CPU       X 980  @ 3.33GHz, 3333 MHz MMX SSE SSE2 SSE3 SSSE3 64 bits DEP
Memory: 12279; free 8094
Display  : 1920x1080 pixels, 32 bpp
------------------------------------------------------------------------------
List of loaded modules:
[00400000] E:\projects\vvvv_50alpha38.2_x64\vvvv.exe
           38.2.4155.0 - 38.2.4155.0
           vvvv - a multipurpose toolkit
           Unit versioning information:
             JCL\source\common $URL$ $Revision$ $Date$
[00790000] C:\Windows\SYSTEM32\ksuser.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           User CSA Library
[00D70000] C:\Windows\SYSTEM32\Icmp.Dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           ICMP DLL
[00D80000] C:\Windows\SYSTEM32\AVIFIL32.DLL
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Microsoft AVI File support library
[00DA0000] C:\Windows\SYSTEM32\MsVfW32.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Microsoft Video for Windows DLL
[00DD0000] C:\Windows\SYSTEM32\wsock32.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Windows Socket 32-Bit DLL
[00FA0000] C:\Windows\SYSTEM32\msimg32.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           GDIEXT Client DLL
[01AF0000] C:\Windows\SYSTEM32\nvwgf2umx.dll
           25.21.14.1967 - 25.21.14.1967
           NVIDIA D3D10 Driver, Version 419.67 
[03F80000] C:\Windows\SYSTEM32\WINNSI.DLL
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Network Store Information RPC interface
[03F90000] C:\Windows\SYSTEM32\iphlpapi.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           IP Helper API
[040B0000] C:\Windows\SYSTEM32\ntmarta.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Windows NT MARTA provider
[04210000] C:\Windows\system32\propsys.dll
           7.0.9600.17041 - 7.00.9600.17031 (winblue_gdr.140221-1952)
           Microsoft Property System
[046D0000] C:\Windows\SYSTEM32\oleacc.dll
           7.2.9600.16384 - 7.2.9600.16384 (winblue_rtm.130821-1623)
           Active Accessibility Core Component
[04740000] C:\Windows\SYSTEM32\DWrite.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Microsoft DirectX Typography Services
[04C50000] C:\Windows\SYSTEM32\security.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Security Support Provider Interface
[04E80000] C:\Windows\SYSTEM32\wtsapi32.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Windows Remote Desktop Session Host Server SDK APIs
[04F00000] C:\Windows\SYSTEM32\MMDevAPI.DLL
           6.3.9600.17031 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           MMDevice API
[04F70000] C:\Windows\SYSTEM32\WINMMBASE.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Base Multimedia Extension API DLL
[05000000] C:\Windows\SYSTEM32\version.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Version Checking and File Installation Libraries
[05010000] C:\Windows\SYSTEM32\winmm.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           MCI API DLL
[052B0000] C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.9600.17031_none_6242a4b3ecbb55a1\comctl32.dll
           6.10.9600.17031 - 6.10 (winblue_rtm.130821-1623)
           User Experience Controls Library
[05510000] C:\Windows\SYSTEM32\dxgi.dll
           6.3.9600.17041 - 6.3.9600.17041 (winblue_gdr.140305-1710)
           DirectX Graphics Infrastructure
[05590000] C:\Windows\SYSTEM32\d3d11.dll
           6.3.9600.17041 - 6.3.9600.17041 (winblue_gdr.140305-1710)
           Direct3D 11 Runtime
[057A0000] C:\Windows\SYSTEM32\AVRT.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Multimedia Realtime Runtime
[05950000] C:\Windows\SYSTEM32\WindowsCodecs.dll
           6.3.9600.16521 - 6.3.9600.16521 (winblue_gdr.140128-1545)
           Microsoft Windows Codecs Library
[05AF0000] C:\Windows\SYSTEM32\dwmapi.dll
           6.3.9600.17031 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Microsoft Desktop Window Manager API
[05CC0000] C:\Windows\SYSTEM32\SHCORE.DLL
           6.3.9600.17031 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           SHCORE
[06360000] C:\Windows\system32\uxtheme.dll
           6.3.9600.17031 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Microsoft UxTheme Library
[064E0000] C:\Windows\SYSTEM32\DEVOBJ.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Device Information Set DLL
[06550000] C:\Windows\SYSTEM32\kernel.appcore.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           AppModel API Host
[068B0000] C:\Windows\SYSTEM32\HID.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Hid User Library
[06930000] C:\Windows\SYSTEM32\WINSTA.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Winstation Library
[06BE0000] C:\Windows\system32\rsaenh.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Microsoft Enhanced Cryptographic Provider
[06D10000] C:\Windows\SYSTEM32\powrprof.dll
           6.3.9600.17031 - 6.3.9600.17031 (winblue_gdr.140221-1952)
           Power Profile Helper DLL
[06F90000] C:\Windows\system32\mswsock.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Microsoft Windows Sockets 2.0 Service Provider
[06FF0000] C:\Windows\SYSTEM32\CRYPTSP.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Cryptographic Service Provider API
[07220000] C:\Windows\SYSTEM32\bcrypt.dll
           6.3.9600.17031 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Windows Cryptographic Primitives Library
[07510000] C:\Windows\SYSTEM32\bcryptPrimitives.dll
           6.3.9600.17031 - 6.3.9600.17031 (winblue_gdr.140221-1952)
           Windows Cryptographic Primitives Library
[07570000] C:\Windows\SYSTEM32\sxs.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Fusion 2.5
[07620000] C:\Windows\SYSTEM32\SSPICLI.DLL
           6.3.9600.16408 - 6.3.9600.16408 (winblue_gdr.130920-1803)
           Security Support Provider Interface
[07650000] C:\Windows\SYSTEM32\CRYPTBASE.DLL
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Base cryptographic API DLL
[07660000] C:\Windows\SYSTEM32\profapi.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           User Profile Basic API
[07710000] C:\Windows\system32\MSASN1.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           ASN.1 Runtime APIs
[07730000] C:\Windows\system32\KERNELBASE.dll
           6.3.9600.17055 - 6.3.9600.17031 (winblue_gdr.140221-1952)
           Windows NT BASE API Client DLL
[07840000] C:\Windows\system32\CRYPT32.dll
           6.3.9600.16431 - 6.3.9600.16431 (winblue_gdr.131015-2301)
           Crypto API32
[07AD0000] C:\Windows\SYSTEM32\cfgmgr32.dll
<11000000> 6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Configuration Manager DLL
[07B20000] C:\Windows\system32\WINTRUST.dll
           6.3.9600.17016 - 6.3.9600.17016 (winblue_gdr.140201-2007)
           Microsoft Trust Verification APIs
[07B70000] C:\Windows\system32\comdlg32.dll
           6.3.9600.17031 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Common Dialogs DLL
[07C10000] C:\Windows\system32\WS2_32.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Windows Socket 2.0 32-Bit DLL
[07C70000] C:\Windows\system32\NSI.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           NSI User-mode interface DLL
[07C80000] C:\Windows\system32\msvcrt.dll
           7.0.9600.16384 - 7.0.9600.16384 (winblue_rtm.130821-1623)
           Windows NT CRT DLL
[07D30000] C:\Windows\system32\SetupApi.dll
           6.3.9600.17031 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Windows Setup API
[07F10000] C:\Windows\system32\gdi32.dll
           6.3.9600.17042 - 6.3.9600.17042 (winblue_gdr.140307-1710)
           GDI Client DLL
[08060000] C:\Windows\system32\oleaut32.dll
<05A80000> 6.3.9600.16506 - 6.3.9600.16506
[08120000] C:\Windows\SYSTEM32\sechost.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Host for SCM/SDDL/LSA Lookup APIs
[08330000] C:\Windows\system32\MSCTF.dll
           6.3.9600.17031 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           MSCTF Server DLL
[08470000] C:\Windows\system32\RPCRT4.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Remote Procedure Call Runtime
[085B0000] C:\Windows\system32\imagehlp.dll
           6.3.9600.16438 - 6.3.9600.16438 (winblue_gdr.131018-1626)
           Windows NT Image Helper
[08630000] C:\Windows\system32\IMM32.DLL
           6.3.9600.17031 - 6.3.9600.17031 (winblue_gdr.140221-1952)
           Multi-User Windows IMM32 API Client DLL
[08670000] C:\Windows\system32\shlwapi.dll
<10000000> 6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Shell Light-weight Utility Library
[086D0000] C:\Windows\system32\advapi32.dll
<10000000> 6.3.9600.17031 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Advanced Windows 32 Base API
[08780000] C:\Windows\system32\ole32.dll
           6.3.9600.17042 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Microsoft OLE for Windows
[08900000] C:\Windows\SYSTEM32\clbcatq.dll
           2001.12.10530.16384 - 2001.12.10530.16384 (winblue_rtm.130821-1623)
           COM+ Configuration Catalog
[08A10000] C:\Windows\system32\PSAPI.dll
           6.3.9600.16384 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Process Status Helper
[08A20000] C:\Windows\system32\combase.dll
           6.3.9600.17031 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Microsoft COM for Windows
[08C10000] C:\Windows\system32\KERNEL32.DLL
           6.3.9600.17056 - 6.3.9600.17031 (winblue_gdr.140221-1952)
           Windows NT BASE API Client DLL
[08D50000] C:\Windows\system32\shell32.dll
           6.3.9600.17055 - 6.3.9600.17031 (winblue_gdr.140221-1952)
           Windows Shell Common Dll
[0A170000] C:\Windows\system32\user32.dll
           6.3.9600.17031 - 6.3.9600.16384 (winblue_rtm.130821-1623)
           Multi-User Windows USER API Client DLL
[0A2F0000] C:\Windows\SYSTEM32\ntdll.dll
           6.3.9600.17031 - 6.3.9600.17031 (winblue_gdr.140221-1952)
           NT Layer DLL
[10000000] E:\projects\vvvv_50alpha38.2_x64\lib\thirdparty\x64\Delmid.dll
           2.60.0.8 - 2.60.008

**Comment by circuitb** [comment]
sorry wrong alert it was a system issue with a bad target to asio x64  dll in registry
